name: Verify cite keys
on: push

jobs:
  verify_cite_keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verify cite keys
        uses: emanuelbuholzer/cite-key-files@main
        with:
          bibliography: test/bibliography.bib
